#SERVER
server:
  port: 8081

#SPRING
spring:
  application:
    name: bank
  config:
    import: configserver:http://localhost:8888
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

#RESOURCE_URL
url:
  CLIENT_API: "https://rickandmortyapi.com/api/character"
  BANK_API: "http://localhost:8085/bank_server"

#AUTHENTICATE
auth-data:
  bankUsername: bank-server
  bankPassword: bank-server
