#SERVER
server:
  port: 8081

#SPRING
spring:
  application:
    name: bank
  config:
    import: configserver:http://localhost:8888
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

#RESOURCE_URL
url:
  CLIENT_API: "https://rickandmortyapi.com/api/character"
  BANK_API: "http://localhost:8085/bank_server"

#AUTHENTICATE
auth-data:
  #  Логин и пароль для подключения к сервису ресурсов банка.
  bankUsername: bank-server
  bankPassword: bank-server

#MANAGEMENT
management:
  endpoints:
    web:
      exposure:
        #        include: env, info, health, *
        include: metrics, prometheus, health
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /api-docs