#SERVER
server:
  port: 8082

#SPRING
spring:
  application:
    name: store_warehouse
  config:
    import: configserver:http://localhost:8888


#EUREKA
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

#RESORECE_URL
url:
  CHARACTER_API: "https://rickandmortyapi.com/api/character"
  SERVER_API: "http://localhost:8084/store_server"

#AUTHENTICATE
auth-data:
  username: store_server
  password: store_server

