#SERVER
server:
  port: 8082

#SPRING
spring:
  application:
    name: store_warehouse
  datasource:
    url: jdbc:postgresql://localhost:5432/db_trading_floor
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      jdbc:
        lob:
          non_contextual_creation: true
      ddl-auto: update
    show-sql: true
  config:
    import: configserver:http://localhost:8888


#EUREKA
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

#RESORECE_URL
url:
  CHARACTER_API: "https://rickandmortyapi.com/api/character"
  BANK_API: "http://localhost:8081/bank/rest"

