server:
  port: 8888

spring:
  application:
    name: ConfigServer

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Avexei2022/CardStoreConfig.git
          basedir: file://c:/tmp/card_store
          default-label: main
