server:
  port: 8888

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Avexei2022/CardStoreConfig.git
          search-path: /tree/main/config
          default-label: main
          search-paths: "{application}"

