#SERVER
server:
  port: 8084

#SPRING
spring:
  application:
    name: store_resource_server
  jpa:
    hibernate:
      jdbc:
        lob:
          non_contextual_creation: true
      ddl-auto: update
    show-sql: true
  config:
    import: configserver:http://localhost:8888
  datasource:
    url: jdbc:postgresql://localhost:5432/db_trading_floor
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: localhost:9092
    bootstrapAddress: localhost:9092
    consumer:
      auto-offset-reset: earliest
      group-id: cardStoreGroup
  rabbitmq:
    binder: localhost


#EUREKA
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

#RESORECE_URL
url:
#  Адрес сервиса Rick and Morty
  CHARACTER_API: "https://rickandmortyapi.com/api/character"
#  Адрес сервера ресурсов банка
  BANK_API: "http://localhost:8085/bank_server"
#  Логин магазина
  DEBIT_USER: "Rick_Sanchez"

#AUTHENTICATE
auth-data:
#  Логин и пароль сервиса ресурсов магазина
  username: store_server
  password: $2y$10$W2JuXPbklBdGi.IORhRapuxgSaPEeq3CHwUTWLDCor.bFFdk6OA3m
#  Логин и пароль для подключения к сервису ресурсов банка
  bankUsername: bank-server
  bankPassword: bank-server

#MANAGEMENT
management:
  endpoints:
    web:
      exposure:
#        include: env, info, health, *
        include: metrics, prometheus, health
  endpoint:
    health:
      show-details: always