#SERVER
server:
  port: 8084

#SPRING
spring:
  application:
    name: store_resource_server
  jpa:
    hibernate:
      jdbc:
        lob:
          non_contextual_creation: true
      ddl-auto: update
    show-sql: true
  config:
    import: configserver:http://localhost:8888
#  datasource:
#    url: jdbc:postgresql://localhost:5432/db_trading_floor
#    username: admin
#    password: admin
#    driver-class-name: org.postgresql.Driver

#EUREKA
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

#RESORECE_URL
url:
  CHARACTER_API: "https://rickandmortyapi.com/api/character"
  BANK_API: "http://localhost:8085/bank_server"

#AUTHENTICATE
auth-data:
  username: store_server
  password: $2y$10$W2JuXPbklBdGi.IORhRapuxgSaPEeq3CHwUTWLDCor.bFFdk6OA3m
  bankUsername: bank-server
  bankPassword: bank-server

#MANAGEMENT
management:
  endpoints:
    web:
      exposure:
#        include: env, info, health, *
        include: metrics, prometheus, health
  endpoint:
    health:
      show-details: always