#SERVER
server:
  port: 8083

#SPRING
spring:
  application:
    name: storefront
  datasource:
    url: jdbc:postgresql://localhost:5432/db_trading_floor
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      jdbc:
        lob:
          non_contextual_creation: true
      ddl-auto: update
    show-sql: true
  config:
    import: configserver:http://localhost:8888

#EUREKA
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

#RESOURCE_URL
url:
  STORAGE_API: "http://localhost:8082/storage/rest"


#management:
#  endpoints:
#    web:
#      exposure:
#        include: metrics,prometheus
