server:
  port: 8083
spring:
  application:
    name: storefront
  config:
    import: configserver:http://localhost:8888
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
url:
  STORAGE_API: "http://localhost:8082/storage/rest"

#management:
#  endpoints:
#    web:
#      exposure:
#        include: metrics,prometheus
