@startuml

interface TrackUserAction{}

class UserActionAspect{
Object userActionLog(ProceedingJoinPoint proceedingJoinPoint)
}

class AuthConfig {
private String bankUsername
private String bankPassword
}

class AuthenticationController{
AuthenticationService service
ResponseEntity<AuthenticationResponse> register(@RequestBody RegisterRequest request)
ResponseEntity<AuthenticationResponse> authenticate(@RequestBody AuthenticationRequest request)
}

class AuthenticationRequest{
private String username
String password
}

class AuthenticationResponse{
private String token
}

class AuthenticationService {
UserRepository repository
PasswordEncoder passwordEncoder
JwtService jwtService
AuthenticationManager authenticationManager
AuthConfig authConfig
AuthenticationResponse register(RegisterRequest request)
AuthenticationResponse authenticate(AuthenticationRequest request)
}

class RegisterRequest{
private String username
private String password
}


class ApplicationConfig {
AuthConfig authConfig
@Bean UserDetailsService userDetailsService()
@Bean AuthenticationProvider authenticationProvider()
@Bean PasswordEncoder passwordEncoder()
@Bean AuthenticationManager authenticationManager(AuthenticationConfiguration config)
}

class BasicConfig {
RestTemplate restTemplate
@Bean UserActionAspect loginAspect()
}

class JwtAuthenticationFilter{
JwtService jwtService
UserDetailsService userDetailsService
void doFilterInternal()
}

class SecurityConfig {
JwtAuthenticationFilter jwtAuthFilter
AuthenticationProvider authenticationProvider
@Bean SecurityFilterChain securityFilterChain(HttpSecurity http)
}

class BankRestController {
BankApiService bankApiService
BankDbService bankDbService
UserDbService userDbService
Counter transactionGoodCounter = Metrics.counter("transactionGoodCounter")
ResponseEntity<Characters> getVisitors(@PathVariable("page") String page)
ResponseEntity<Message> addToBank(@PathVariable("id") Integer id)
ResponseEntity<Message> deleteCandidateFromBank(@PathVariable("id") Integer id)
ResponseEntity<Characters> getPageCandidates(@PathVariable("page") String page)
ResponseEntity<Message> addCandidateToClient(@PathVariable("id") Integer id)
ResponseEntity<Message> deleteClient(@PathVariable("id") Long id)
ResponseEntity<ClientsList> getPageCardsInSale(@PathVariable("page") Integer page)
ResponseEntity<Message> updateClient(Client client)
ResponseEntity<Message> transaction(@RequestBody Transaction transaction)
ResponseEntity<User> findUserByName(@PathVariable("name") String name)
}

class BankRestExceptionController {
ExceptionBody excessAmount(ExcessAmountException e)
ExceptionBody resourceNotFound(ResourceNotFoundException e)
}

class Client {
Long id
CharacterResult clientDetail
BigDecimal balance
}

class ClientsList {
ClientsListInfo info
List<Client> clientList
}

class ClientsListInfo {
Long count
Integer pages
Integer next
Integer current
Integer prev
}

class ExceptionBody {
String message
LocalDateTime dateTime
}

class ExcessAmountException extends RuntimeException{
ExcessAmountException(String message)
}

class ResourceNotFoundException  extends RuntimeException{
ResourceNotFoundException(String message)
}

class Message {
String message
}

class Transaction {
String creditName
String debitName
BigDecimal transferAmount
}

enum Role {
    USER,
    ADMIN,
    BANK
}

class User implements UserDetails {
Long id
String username
String password
Role role
Boolean enabled
String email
Boolean isSubscribe
Collection<? extends GrantedAuthority> getAuthorities()
boolean isAccountNonExpired()
boolean isAccountNonLocked()
boolean isCredentialsNonExpired()
boolean isEnabled()
}

class CharacterInfo {
Integer count
Integer pages
String next
String prev
}

class CharacterResult{
Integer id
String name
String status
String species
String type
String gender
String image
String url
Date created
}

class Characters {
CharacterInfo info
List<CharacterResult> results
}

interface ClientsRepository extends JpaRepository<Client, Long> {
}

interface UserRepository extends JpaRepository<User, Long> {
Optional<User> findUserByUsername(String username)
}

interface VisitorRepository extends JpaRepository<CharacterResult, Integer> {
}

interface BankApiService {
Characters getAllCharacters(String page)
Message saveOneCharacterById(Integer id)
}

class BankApiServiceImpl implements BankApiService {
BankDbService characterDbService
BasicConfig basicConfig
RestTemplate restTemplate
HttpHeaders headers
HttpEntity<String> getRequestEntity()
Characters getAllCharacters(String page)
CharacterInfo getCharacterInfo(Characters allCharacters)
Message saveOneCharacterById(Integer id)
}

interface BankDbService {
void saveOneVisitor(CharacterResult characterResult
Characters getPageBankCandidates(Integer page)
Message deleteVisitorById(Integer id)
Message saveOneClientById(Integer id)
List<CharacterResult> getAllClients()
ClientsList getPageBankClients(Integer page)
Message deleteClientById(Long id)
Message saveClient(Client client)
Client findClientById(Long id)
Client findClientByName(String name)
void transaction(Transaction transaction)
}

class BankDbServiceImpl implements BankDbService{
VisitorRepository visitorRepository
ClientsRepository clientsRepository
void saveOneVisitor(CharacterResult characterResult)
Characters getPageBankCandidates(Integer page)
Message deleteVisitorById(Integer id)
Message saveOneClientById(Integer id)
List<CharacterResult> getAllClients()
ClientsList getPageBankClients(Integer page)
Message deleteClientById(Long id)
Message saveClient(Client client)
Client findClientById(Long id)
Client findClientByName(String name)
void transaction(Transaction transaction)
}

interface UserDbService {
User findUserByUsername(String username)
}

class UserDbServiceImpl implements UserDbService{
UserRepository userRepository
User findUserByUsername(String username)
}

class JwtService {
String SECRET_KEY =
String extractUsername(String token)
<T> T extractClaim(String token, Function<Claims, T> claimsResolver)
String generateToken(UserDetails userDetails)
 String generateToken(
            Map<String, Object> extraClaims,
            UserDetails userDetails
    )
boolean isTokenValid(String token, UserDetails userDetails)
boolean isTokenExpired(String token)
Date extractExpiration(String token)
Claims extractAllClaims(String token)
Key getSigningKey()
}

class BankServerApp {
void main(String[] args)
@Bean RestTemplate template()
@Bean HttpHeaders headers()
}



@enduml